apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: haproxy:5432
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: grafana
      sslmode: 'disable'
      maxOpenConns: 100 
      maxIdleConns: 100 
      maxIdleConnsAuto: true 
      connMaxLifetime: 14400 
      postgresVersion: 1500
      timescaledb: false